### ISSUE TITLE
GR Supra inventory missing

### ISSUE THREAD

**Issue by KashubaK** [major/yotagrabber#32]
The `output` directory seems to be missing data for the GR Supra.

**Comment by major** [comment]
Ah, you found something interesting! Toyota has specific strings for their models, like `tundra` and `4runner` and these usually match between the models list and the inventory from the graphql API.

**HOWEVER,** there are two notable exceptions when going from the model names to the graphql query:

* `grsupra` becomes `supra`
* `gr86` becomes `86`

I'll need to add some hacks to the script to account for that.

**Comment by major** [comment]
@KashubaK Should be fixed now. I'm running a test to verify: https://github.com/major/yotagrabber/actions/runs/5444917434

**Comment by major** [comment]
@KashubaK Success! https://flatgithub.com/major/yotagrabber?filename=output%2Fsupra.csv

**Comment by KashubaK** [comment]
This is awesome! Thanks so much. 🙌
